services:
  auth-service:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: auth-service:dev
    stdin_open: true
    tty: true
    ports:
      - "5501:5501"
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: pizza-auth-service-volume-container
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - pizza-auth-service-volume:/var/lib/postgresql/data

volumes:
  pizza-auth-service-volume:
    external: true
