services:
  nodeservertemplate:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: nodeservertemplate:dev
    stdin_open: true
    tty: true
    ports:
      - "5501:5501"
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
